name: mdmoney
version: 1.0.0
homepage: https://github.com/marchdev-tk/mdmoney
repository: https://github.com/marchdev-tk/mdmoney
issue_tracker: https://github.com/marchdev-tk/mdmoney/issues
description: mdmoney description

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  meta: ^1.15.0
  decimal: ^3.0.2

dev_dependencies:
  flutter_lints: ^5.0.0
  test: ^1.25.7
