/// TODO
///
/// For more info about currencies visit:
/// - [ISO 4217 Wikipedia](https://en.wikipedia.org/wiki/ISO_4217#Active_codes_(List_One))
/// - [ISO 4217-1 with currency symbols](https://gist.github.com/sgraaf/21d5919940844c9f0c12f147ed45953d)
enum Currency {
  aed('AED', '784', 'د.إ'),
  afn('AFN', '971', '؋'),
  all('ALL', '008', 'Lek'),
  amd('AMD', '051', 'Դ'),
  ang('ANG', '532', 'ƒ'),
  aoa('AOA', '973', 'is'),
  ars('ARS', '032', r'$'),
  aud('AUD', '036', r'$'),
  awg('AWG', '533', 'ƒ'),
  azn('AZN', '944', '₼'),
  bam('BAM', '977', 'КМ'),
  bbd('BBD', '052', r'$'),
  bdt('BDT', '050', '৳'),
  bgn('BGN', '975', 'лв'),
  bhd('BHD', '048', 'ب.د'),
  bif('BIF', '108', '₣'),
  bmd('BMD', '060', r'$'),
  bnd('BND', '096', r'$'),
  bob('BOB', '068', 'Bs.'),
  bov('BOV', '984', 'Mvdol'),
  brl('BRL', '986', r'R$'),
  bsd('BSD', '044', r'$'),
  btn('BTN', '064', 'Nu.'),
  bwp('BWP', '072', 'P'),
  byn('BYN', '933', 'p.'),
  bzd('BZD', '084', r'$'),
  cad('CAD', '124', r'$'),
  cdf('CDF', '976', '₣'),
  che('CHE', '947', ''),
  chf('CHF', '756', '₣'),
  chw('CHW', '948', ''),
  clf('CLF', '990', 'UF'),
  clp('CLP', '152', r'$'),
  cop('COP', '170', r'$'),
  cou('COU', '970', ''),
  crc('CRC', '188', '₡'),
  cuc('CUC', '931', r'CUC$'),
  cup('CUP', '192', r'$'),
  cve('CVE', '132', r'$'),
  czk('CZK', '203', 'Kč'),
  djf('DJF', '262', '₣'),
  dkk('DKK', '208', 'kr'),
  dop('DOP', '214', r'$'),
  dzd('DZD', '012', 'د.ج'),
  egp('EGP', '818', '£'),
  ern('ERN', '232', 'Nfk'),
  etb('ETB', '230', 'Br'),
  eur('EUR', '978', '€'),
  fjd('FJD', '242', r'$'),
  fkp('FKP', '238', '£'),
  gbp('GBP', '826', '£'),
  gel('GEL', '981', 'ლ'),
  ghs('GHS', '936', '₵'),
  gip('GIP', '292', '£'),
  gmd('GMD', '270', 'D'),
  gnf('GNF', '324', '₣'),
  gtq('GTQ', '320', 'Q'),
  gyd('GYD', '328', r'$'),
  hkd('HKD', '344', r'$'),
  hnl('HNL', '340', 'L'),
  htg('HTG', '332', 'G'),
  huf('HUF', '348', 'Ft'),
  idr('IDR', '360', 'Rp'),
  ils('ILS', '376', '₪'),
  inr('INR', '356', '₨'),
  iqd('IQD', '368', 'ع.د'),
  irr('IRR', '364', '﷼'),
  isk('ISK', '352', 'Kr'),
  jmd('JMD', '388', r'$'),
  jod('JOD', '400', 'د.ا'),
  jpy('JPY', '392', '¥'),
  kes('KES', '404', 'Sh'),
  kgs('KGS', '417', 'с'),
  khr('KHR', '116', '៛'),
  kmf('KMF', '174', '₣'),
  kpw('KPW', '408', '₩'),
  krw('KRW', '410', '₩'),
  kwd('KWD', '414', 'د.ك'),
  kyd('KYD', '136', r'$'),
  kzt('KZT', '398', '〒'),
  lak('LAK', '418', '₭'),
  lbp('LBP', '422', 'ل.ل'),
  lkr('LKR', '144', 'Rs'),
  lrd('LRD', '430', r'$'),
  lsl('LSL', '426', 'L'),
  lyd('LYD', '434', 'ل.د'),
  mad('MAD', '504', 'د.م.'),
  mdl('MDL', '498', 'L'),
  mga('MGA', '969', 'MK'),
  mkd('MKD', '807', 'ден'),
  mmk('MMK', '104', 'K'),
  mnt('MNT', '496', '₮'),
  mop('MOP', '446', 'P'),
  mru('MRU', '929', 'UM'),
  mur('MUR', '480', '₨'),
  mvr('MVR', '462', 'ރ'),
  mwk('MWK', '454', 'MK'),
  mxn('MXN', '484', r'$'),
  mxv('MXV', '979', ''),
  myr('MYR', '458', 'RM'),
  mzn('MZN', '943', 'MTn'),
  nad('NAD', '516', r'$'),
  ngn('NGN', '566', '₦'),
  nio('NIO', '558', r'C$'),
  nok('NOK', '578', 'kr'),
  npr('NPR', '524', '₨'),
  nzd('NZD', '554', r'$'),
  omr('OMR', '512', 'ر.ع.'),
  pab('PAB', '590', 'B/.'),
  pen('PEN', '604', 'S/.'),
  pgk('PGK', '598', 'K'),
  php('PHP', '608', '₱'),
  pkr('PKR', '586', '₨'),
  pln('PLN', '985', 'zł'),
  pyg('PYG', '600', '₲'),
  qar('QAR', '634', 'ر.ق'),
  ron('RON', '946', 'L'),
  rsd('RSD', '941', 'din'),
  cny('CNY', '156', '¥'),
  rwf('RWF', '646', '₣'),
  sar('SAR', '682', 'ر.س'),
  sbd('SBD', '090', r'$'),
  scr('SCR', '690', '₨'),
  sdg('SDG', '938', '£'),
  sek('SEK', '752', 'kr'),
  sgd('SGD', '702', r'$'),
  shp('SHP', '654', '£'),
  sle('SLE', '925', 'Le'),
  sll('SLL', '694', 'Le'),
  sos('SOS', '706', 'Sh'),
  srd('SRD', '968', r'$'),
  ssp('SSP', '728', '£'),
  stn('STN', '930', 'Db'),
  svc('SVC', '222', '₡'),
  syp('SYP', '760', '£'),
  szl('SZL', '748', 'L'),
  thb('THB', '764', '฿'),
  tjs('TJS', '972', 'ЅМ'),
  tmt('TMT', '934', 'm'),
  tnd('TND', '788', 'د.ت'),
  top('TOP', '776', r'T$'),
  try_('TRY', '949', '₺'),
  ttd('TTD', '780', r'$'),
  twd('TWD', '901', r'NT$'),
  tzs('TZS', '834', 'Sh'),
  uah('UAH', '980', '₴'),
  ugx('UGX', '800', 'Sh'),
  usd('USD', '840', r'$'),
  usn('USN', '997', ''),
  uyi('UYI', '940', ''),
  uyu('UYU', '858', r'$U'),
  uyw('UYW', '927', ''),
  uzs('UZS', '860', 'Sʻ'),
  ved('VED', '926', 'Bs.'),
  ves('VES', '928', 'Bs.'),
  vnd('VND', '704', '₫'),
  vuv('VUV', '548', 'Vt'),
  wst('WST', '882', 'T'),
  xaf('XAF', '950', '₣'),
  xag('XAG', '961', ''),
  xau('XAU', '959', ''),
  xba('XBA', '955', ''),
  xbb('XBB', '956', ''),
  xbc('XBC', '957', ''),
  xbd('XBD', '958', ''),
  xcd('XCD', '951', r'$'),
  xdr('XDR', '960', 'SDR'),
  xof('XOF', '952', '₣'),
  xpd('XPD', '964', ''),
  xpf('XPF', '953', '₣'),
  xpt('XPT', '962', ''),
  xsu('XSU', '994', ''),
  xts('XTS', '963', ''),
  xua('XUA', '965', ''),
  xxx('XXX', '999', ''),
  yer('YER', '886', '﷼'),
  zar('ZAR', '710', 'R'),
  zwm('ZMW', '967', 'ZK'),
  zwl('ZWL', '932', r'$'),
  unknown('unknown', 'unknown', 'unknown');

  const Currency(this.code, this.number, this.icon);

  factory Currency.parse(String currency) {
    return values.firstWhere(
      (c) =>
          c.code == currency.toUpperCase() ||
          c.number == currency ||
          c.icon == currency,
      orElse: () => Currency.unknown,
    );
  }

  static Currency? tryParse(String? currency) {
    if (currency?.isNotEmpty != true) {
      return null;
    }

    return Currency.parse(currency!);
  }

  static Currency $default = Currency.uah;
  static void setDefaultCurrency(Currency currency) => $default = currency;

  final String code;
  final String number;
  final String icon;

  bool get isDefault => code == $default.code;

  @override
  String toString() => icon.isNotEmpty ? icon : code;
}
